version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DATABASE_URL=jdbc:postgresql://postgres:5432/rockOpsDB?user=postgres&password=1234
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_PUBLIC_URL=http://localhost:9002
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=rockops
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,http://localhost:3000
    depends_on:
      - postgres
      - minio
  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"  # Using 5433 to avoid conflict with your local postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rockOpsDB
    volumes:
      - postgres_data_local:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    ports:
      - "9002:9000"  # Using 9002 to avoid conflict
      - "9003:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data_local:/data

volumes:
  postgres_data_local:
  minio_data_local: