services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DATABASE_URL=jdbc:postgresql://postgres:5432/rockOpsDB?user=postgres&password=1234
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_PUBLIC_URL=http://localhost:9002
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=rockops
      - CORS_ALLOWED_ORIGINS=https://rock-ops.vercel.app,http://localhost:5173
      - PORT=8080
    depends_on:
      - postgres
      - minio
    networks:
      - rockops-network

  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rockOpsDB
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    networks:
      - rockops-network

  minio:
    image: minio/minio:latest
    ports:
      - "9002:9000"
      - "9003:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data_test:/data
    networks:
      - rockops-network

networks:
  rockops-network:
    driver: bridge

volumes:
  postgres_data_test:
  minio_data_test: 