version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: RockOpsDBContainer
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rockOpsDB
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - rockops-network

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - rockops-network

volumes:
  pg_data:
  minio_data:

networks:
  rockops-network:
    driver: bridge