version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - cd frontend
      - npm install
  build:
    commands:
      - echo Building React app...
      - npm run build
  post_build:
    commands:
      - echo Deploying to S3...
      - aws s3 sync dist/ s3://rockops/ --delete

artifacts:
  files:
    - '**/*'
  base-directory: frontend/dist
