version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: Rock4MiningDBContainer
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rockOpsDB
    volumes:
      - pg_data:/var/lib/postgresql/data

  minio:
    image:  quay.io/minio/minio:latest  # Use a stable release
    container_name: minio
    restart: always
    ports:
      - "9000:9000"  # MinIO API Port
      - "9001:9001"  # MinIO Web UI Port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  pg_data:  # Keeps PostgreSQL data safe
  minio_data:  # New volume for MinIO
