version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: RockOpsDBContainer-client
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rockOpsDB
    volumes:
      - pg_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio-client
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_SERVER_URL=http://localhost:9000  # Add this line!
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: always

  backend:
    image: eclipse-temurin:23-jre
    container_name: rockops-backend
    volumes:
      - ./app.jar:/app.jar
    command: java -jar /app.jar --spring.profiles.active=docker
    depends_on:
      - postgres
      - minio
    ports:
      - "8080:8080"
    restart: always

  frontend:
    image: nginx:alpine
    container_name: rockops-frontend
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:80"
    restart: always

volumes:
  pg_data:
  minio_data: